development:
  adapter: postgresql
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  database: rails1_app

production:
  adapter: postgresql
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  database: rails1_app























